### ISSUE TITLE
Matching password from linux /etc/shadow

### ISSUE THREAD

**Issue by ybizeul** [go-crypt/crypt#30]
I'm probably missing something obvious, I'm trying to verify a password using the following code :

```
if _, err := crypt.CheckPassword(password, "$5$EChJ2Sf8i9S/3eNd$x4GZ1KVDGLLOgcGfMrytc0DzjhJUDGD6fJMsLR53Ui5"); err != nil {
	return err
}
```

It seems this package is expecting some metadata with an additional `$` separator but can't figure it out

**Comment by james-d-elliott** [comment]
Yeah it's expecting rounds, per the spec it should be able to be omitted when the rounds is equal to 5000 which is probably the case here. The following should work but I'll look at implementing this feature.

```go
if _, err := crypt.CheckPassword(password, "$5$rounds=5000$EChJ2Sf8i9S/3eNd$x4GZ1KVDGLLOgcGfMrytc0DzjhJUDGD6fJMsLR53Ui5"); err != nil {
	return err
}
```

**Comment by james-d-elliott** [comment]
@ybizeul added this feature and it's tagged v0.2.14.
