### ISSUE TITLE
Allos changing the `bcrypt` identifier when Encoding  the digest.

### ISSUE THREAD

**Issue by shamil** [go-crypt/crypt#70]
Unless I misunderstood something,  there is no way to change the Algorithm identifier. I see it's hardocded to `AlgIdentifier` (`2b`). 

https://github.com/go-crypt/crypt/blob/c160fb3a13cbf8bc0ee5e3ad383897d55734eacc/algorithm/bcrypt/digest.go#L55-L58

**Comment by james-d-elliott** [comment]
There isn't.
